# 运行模式(debug:调试,test:测试,release:正式)
RunMode = "debug"

# 是否启用swagger
Swagger = true

# 启动时是否打印配置参数
PrintConfig = true

[HTTP]
# http监听地址
Host = "0.0.0.0"
# http监听端口
Port = 18899
# 证书路径
CertFile = ""
# 证书密钥
KeyFile = ""
# http优雅关闭等待超时时长(单位秒)
ShutdownTimeout = 300
# 允许的最大内容长度(128M)
MaxContentLength = 134217728
# 允许输出的最大日志长度
MaxLoggerLength = 4096

[Log]
# 日志级别(1:fatal 2:error,3:warn,4:info,5:debug,6:trace)
Level = 5
# 日志格式（支持输出格式：text/json）
Format = "text"
# 日志输出(支持：stdout/stderr/file)
Output = "stderr"
# 指定日志输出的文件路径
OutputFile = "data/go-kriging-service.log"


# 服务监控(GOPS:https://github.com/google/gops)
[Monitor]
# 是否启用
Enable = false
# HTTP的监听地址和端口
Addr = "127.0.0.1:16060"
# 配置文件目录(为空则使用默认目录)
ConfigDir = ""


# 请求频率限制 功能未完成
[RateLimiter]
# 是否启用
Enable = false
# 每分钟每个用户允许的最大请求数量
Count = 300

[CORS]
# 是否启用
Enable = true
# 允许跨域请求的域名列表(*表示全部允许)
AllowOrigins = ["*"]
# 允许跨域请求的请求方式列表
AllowMethods = ["GET","POST","PUT","DELETE","PATCH"]
# 允许客户端与跨域请求一起使用的非简单标头的列表
AllowHeaders = ['content-type', 'authorization']
# 请求是否可以包含cookie，HTTP身份验证或客户端SSL证书等用户凭据
AllowCredentials = true
# 可以缓存预检请求结果的时间（以秒为单位）
MaxAge = 7200

[GZIP]
# 是否启用
Enable = false
# 排除的文件扩展名
ExcludedExtentions = [".png",".gif",".jpeg",".jpg"]
# 排除的请求路径
ExcludedPaths = []

